name: Check links

on:
  workflow_dispatch:
  schedule:
    - cron: "5 18 * * *"

permissions:
  contents: read

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@f1da3291e1d03cbe11a413ae9f16b62fec99e6b6
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: --exclude-all-private --exclude-mail --require-https --verbose --no-progress './**/*.md' './**/*.html'
          fail: true
