name: Check links

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: --exclude-all-private --exclude-mail --include-verbatim --require-https --verbose --no-progress './**/*.md' './**/*.html'
          fail: true
