name: Check links

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@97189f2c0a3c8b0cb0e704fd4e878af6e5e2b2c5
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: --exclude-all-private --exclude-mail --include-verbatim --require-https --verbose --no-progress './**/*.md' './**/*.html'
          fail: true
